### ISSUE TITLE
Expired transaction error.

### ISSUE THREAD

**Issue by amashura** [autoalmosteverything/AlienWorlds#4]
1. Could you make a captcha solver based on anti-captcha? Either something is wrong in the code, or 2captcha takes so long to solve the captcha that the transaction time passes.
2. After a CPU error, the window closes and waits for the full recharge time, is this how it should be?
3. After each mine, the browser window closes, is it supposed to be?

**Comment by autoalmosteverything** [comment]
1. I will add more solving captcha services in the further updates. The script will try 3 times if 2captcha takes more than 1m30s to solve the captcha. Or give notification if all of them are expired.
2. At this time, the script doesn't care about the error. So they may repeat many "out of CPU" errors every 5 minutes before mining successfully again.
3. That's right. It's good for the performance of your computer. While there is nothing to do, no browser turns on. The browser will turn on after 5 minutes then do new mining.
